import { BaseComponent, html } from 'framework';

export class ChatSideNav extends BaseComponent {
  constructor() {
    super();
    this.chatFriendsGroups = this.slice('chatFriendsGroups');

    // TODO should be set by query once we can get data from server
    this.chatFriendsGroups.actions.setActiveFriendOrGroup('Lumen');
  }

  render() {
    this.rootCSSClasses('chat-side-nav');

    return html`
      <div class="chat-side-nav-scrollbar chat-side-nav-inner h-100 d-flex flex-column gap-4 position-relative">
        <chat-side-nav-top-bar />

        <!-- This will be autogenerated once we are able to get data from the server -->
        ${this.chatFriendsGroups.state.activeTab === 'groups'
        ? html`
              <div class="pe-2 d-flex flex-column gap-4">
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                </chat-side-nav-group>
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                </chat-side-nav-group>
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="John Doe" />
                </chat-side-nav-group>
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                </chat-side-nav-group>
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="Jane Doe" />
                </chat-side-nav-group>
                <chat-side-nav-group name="Lumen">
                  <chat-side-nav-person name="John Doe" />
                  <chat-side-nav-person name="Jane Doe" />
                </chat-side-nav-group>
              </div>
            `
        : html`
              <div class="pe-2 d-flex flex-column gap-3">
                <chat-side-nav-person name="John Doe" />
                <chat-side-nav-person name="John Doe" />
                <chat-side-nav-person name="John Doe" />
                <chat-side-nav-person name="John Doe" />
                <chat-side-nav-person name="John Doe" />
                <chat-side-nav-person name="John Doe" />
              </div>
            `
      }
      </div>
    `;
  }
}
